mode: "blocklist"
countries:
  - "CN"
  - "RU"
block_private_ips: true
geoip_db_path: "/app/GeoLite2-Country.mmdb"
listen_addr: ":8080"
debug: true
maxmind_account_id_file: "/secrets/maxmind-creds/MAXMIND_ACCOUNT_ID"
maxmind_license_key_file: "/secrets/maxmind-creds/MAXMIND_LICENSE_KEY"
maxmind_edition_id: "GeoLite2-Country"
update_check_interval_hours: 24
