apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "maxmind-geoip-authz.fullname" . }}
  labels:
    {{- include "maxmind-geoip-authz.labels" . | nindent 4 }}
data:
  config.yaml: |
    mode: {{ .Values.config.mode | quote }}
    countries:
    {{- range .Values.config.countries }}
      - {{ . | quote }}
    {{- end }}
    private_ip_action: {{ .Values.config.private_ip_action }}
    unknown_action: {{ .Values.config.unknown_action }}
    {{- $dbFilename := .Values.geoipDatabase.dbFilename | default (printf "%s.mmdb" .Values.geoipupdate.editionIDs) }}
    {{- $db := .Values.config.geoip_db_path | default (printf "%s/%s" .Values.geoipDatabase.mountPath $dbFilename) }}
    geoip_db_path: {{ $db | quote }}
    listen_addr: {{ .Values.config.listen_addr | quote }}
    debug: {{ .Values.config.debug }}
