apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "maxmind-geoip-authz.fullname" . }}
  labels:
    {{- include "maxmind-geoip-authz.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "maxmind-geoip-authz.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "maxmind-geoip-authz.selectorLabels" . | nindent 8 }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "maxmind-geoip-authz.serviceAccountName" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          workingDir: /app
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: config
              mountPath: /app/config.yaml
              subPath: config.yaml
            - name: geoip-db
              mountPath: {{ .Values.geoipDatabase.mountPath }}
      volumes:
        - name: config
          configMap:
            name: {{ include "maxmind-geoip-authz.fullname" . }}
        - name: geoip-db
          persistentVolumeClaim:
            claimName: {{ default (include "maxmind-geoip-authz.fullname" .) .Values.geoipDatabase.pvc.existingClaim }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
